### ISSUE TITLE
关于C++转换的问题

### ISSUE THREAD

**Issue by XanaduAPI** [dkw72n/idb#2]
请问一下这个库有C/C++的版本吗？
或者有什么可以帮到我转换为C/C++的，比如一些原理文档什么的。
非常感谢。

**Comment by dkw72n** [comment]
c++ 的话, https://github.com/troybowman/dtxmsg 有

看协议的话建议看 https://github.com/alibaba/taobao-iphone-device 他代码写的比较干净, 参考文档也比较全.

**Comment by XanaduAPI** [comment]
好的，非常感谢。
